package org.rs09.consts

object Vars {
    //QUESTS
    const val VARP_QUEST_CHOMPY = 293
    const val VARP_QUEST_ELEMENTAL_WORKSHOP = 299

    const val VARBIT_QUEST_CHOMPY_SPITROAST = 1770
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_READ_BOOK = 2056
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_SLASHED_BOOK = 2057
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_LEFT_WATERCONTROLS = 2058
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_RIGHT_WATERCONTROLS = 2059
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_WATER_WHEEL = 2060
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_LIT_FURNACE = 2062
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_FIXED_BELLOWS = 2063
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_ITEM_TRACKER = 2064
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_INITIAL_ENTRY = 2065
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_QUEST_COMPLETE = 2067

    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_II = 2639
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_II_KEY = 2640
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_II_HATCH = 2641
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_II_PIPE = 2650
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_II_PIN_COG_I = 2655
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_II_PIN_COG_II = 2656
    const val VARBIT_QUEST_ELEMENTAL_WORKSHOP_II_PIN_COG_III = 2657

    const val VARBIT_QUEST_PLAGUE_CITY_EDMOND_TUNNELS = 1783
    const val VARBIT_QUEST_PLAGUE_CITY_RESCUE_ELENA = 1784
    const val VARBIT_QUEST_PLAGUE_CITY_MUD_PILE = 1785
    const val VARBIT_QUEST_PLAGUE_CITY_SEWER = 1787

    const val VARBIT_MINI_QUEST_MOGRE = 1344

    //SCENERY
    const val VARP_SCENERY_ABYSS = 491
    const val VARBIT_SCENERY_ABYSS_OBSTACLES = 625

    //INTERFACES
    const val VARP_IFACE_BANK_INSERT_MODE = 304
    const val VARP_IFACE_BANK_NOTE_MODE = 115

    // S700 : BANKPIN INTERFACE PIN TEXT LEFT TO RIGHT, TOP TO BOTTOM  (VARP 562)
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_0 = 997
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_1 = 998
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_2 = 999
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_3 = 1000
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_4 = 1001
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_5 = 1002
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_6 = 1003
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_7 = 1004
    // S700 : BANKPIN INTERFACE PIN TEXT CONTINUED... (VARP 563)
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_8 = 1005
    const val VARBIT_IFACE_BANKPIN_MAIN_PIN_SLOT_9 = 1006
    // S699 : >= 2 Only show exit(on exit -> S696) / < 2 "I don't know it" (open iface BANKPIN_SETTINGS_14)
    const val VARBIT_IFACE_BANKPIN_MAIN_EXIT_BOX = 1009
    // S697/698 : Click the FIRST(0), SECOND(1), THIRD(2), FOURTH(3), THANKS(4) / * * * * to ? ? ? ?
    const val VARBIT_IFACE_BANKPIN_MAIN_INFO_DIGIT_TEXT = 1010

    const val VARBIT_GRAVE_DISPLAY = 4191

    const val VARBIT_IFACE_BANK_INSERT_MODE = 7000
    const val VARBIT_IFACE_BANK_NOTE_MODE = 7001


}
